<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Chrome Test Suite" duration-ms="47151" started-at="2020-02-02T15:13:41Z" finished-at="2020-02-02T15:14:28Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="47151" started-at="2020-02-02T15:13:41Z" finished-at="2020-02-02T15:14:28Z">
      <class name="com.Test.testCases.CreateRechargeTest">
        <test-method status="PASS" signature="launchApplication(java.lang.String)[pri:0, instance:com.Test.testCases.CreateRechargeTest@10dba097]" name="launchApplication" is-config="true" duration-ms="32353" started-at="2020-02-02T15:13:09Z" finished-at="2020-02-02T15:13:41Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[GC]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method status="FAIL" signature="verifyTelecelRecharge(java.util.Hashtable)[pri:0, instance:com.Test.testCases.CreateRechargeTest@10dba097]" name="verifyTelecelRecharge" duration-ms="46269" started-at="2020-02-02T15:13:42Z" data-provider="excelData" finished-at="2020-02-02T15:14:28Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{emailId=test@test.com, cvvNumber=111, number=5523261151, recarga=10, operador=Telcel, expiryYear=2025, userName=marze.zr@gmail.com, password=123456, expiryMonth=11, cardHolderName=Test, cardNumber=4111111111111111}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [Recarga   Recarga Saldo   de Telcel   al número 5523261151   de   $10 pesos] but found [Recarga   Recarga Saldo  de Telcel  al número 5523261151  de   $10 pesos]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Recarga   Recarga Saldo   de Telcel   al número 5523261151   de   $10 pesos] but found [Recarga   Recarga Saldo  de Telcel  al número 5523261151  de   $10 pesos]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at com.Test.testCases.CreateRechargeTest.verifyTelecelRecharge(CreateRechargeTest.java:47)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyTelecelRecharge -->
        <test-method status="PASS" signature="closeApplication()[pri:0, instance:com.Test.testCases.CreateRechargeTest@10dba097]" name="closeApplication" is-config="true" duration-ms="4764" started-at="2020-02-02T15:14:29Z" finished-at="2020-02-02T15:14:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApplication -->
      </class> <!-- com.Test.testCases.CreateRechargeTest -->
    </test> <!-- Test -->
  </suite> <!-- Chrome Test Suite -->
</testng-results>
